<script type='text/javascript' src='https://c.la1-c2cs-iad.salesforceliveagent.com/content/g/js/41.0/deployment.js'></script>
<script type="text/javascript">
console.log('liveAgent Init 1');
liveagent.init('https://d.la1-c2cs-iad.salesforceliveagent.com/chat', '572g000000000YT', '00Dg0000001qRGK');
console.log('liveAgent Init 2');
if (!window._laq) { window._laq = []; }
window._laq.push(function(){liveagent.showWhenOnline('573g0000000012d', document.getElementById('liveagent_button_online_573g0000000012d'));
liveagent.showWhenOffline('573g0000000012d', document.getElementById('liveagent_button_offline_573g0000000012d'));
});
</script>
